services:
    cliproxyapi:
        image: ${CLI_PROXY_IMAGE:-ghcr.io/minervacap2022/cliproxyapi:latest}
        pull_policy: always
        container_name: cliproxyapi
        network_mode: host
        environment:
            - MANAGEMENT_STATIC_PATH=/CLIProxyAPI/panel/management.html
        volumes:
            - ${CLI_PROXY_CONFIG_PATH:-/opt/cpa/config.yaml}:/CLIProxyAPI/config.yaml
            - ${CLI_PROXY_AUTH_PATH:-/opt/cpa/auths}:/root/.cli-proxy-api
            - ${CLI_PROXY_LOG_PATH:-/opt/cpa/logs}:/CLIProxyAPI/logs
            - ${CLI_PROXY_PLUGIN_PATH:-/opt/cpa/plugins}:/CLIProxyAPI/plugins
            - ./panel/management.html:/CLIProxyAPI/panel/management.html:ro
        restart: unless-stopped
